/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "outline": "#727785",
        "secondary": "#505f76",
        "inverse-primary": "#adc6ff",
        "on-tertiary-fixed": "#002113",
        "primary-fixed-dim": "#adc6ff",
        "tertiary-fixed": "#6ffbbe",
        "tertiary-container": "#00855b",
        "background": "#faf8ff",
        "surface-container-lowest": "#ffffff",
        "error-container": "#ffdad6",
        "on-surface-variant": "#424754",
        "inverse-on-surface": "#eef0ff",
        "surface-dim": "#d2d9f4",
        "on-primary-fixed-variant": "#004395",
        "surface-container": "#eaedff",
        "surface-container-highest": "#dae2fd",
        "on-background": "#131b2e",
        "on-error": "#ffffff",
        "secondary-fixed-dim": "#b7c8e1",
        "on-primary-container": "#fefcff",
        "surface-variant": "#dae2fd",
        "on-error-container": "#93000a",
        "surface-tint": "#005ac2",
        "tertiary": "#006947",
        "primary-fixed": "#d8e2ff",
        "outline-variant": "#c2c6d6",
        "secondary-fixed": "#d3e4fe",
        "primary-container": "#2170e4",
        "on-primary": "#ffffff",
        "on-secondary-fixed-variant": "#38485d",
        "on-secondary-fixed": "#0b1c30",
        "on-tertiary": "#ffffff",
        "secondary-container": "#d0e1fb",
        "primary": {
          DEFAULT: '#0058be',
          hover: '#004395',
          light: '#EFF6FF',
          50: '#EFF6FF',
          100: '#DBEAFE',
          500: '#2563EB',
          600: '#0058be',
          700: '#004395',
        },
        "surface-container-low": "#f2f3ff",
        "surface-container-high": "#e2e7ff",
        "on-secondary": "#ffffff",
        "surface-bright": "#faf8ff",
        "on-primary-fixed": "#001a42",
        "on-tertiary-fixed-variant": "#005236",
        "tertiary-fixed-dim": "#4edea3",
        "surface": "#faf8ff",
        "on-tertiary-container": "#f5fff6",
        "inverse-surface": "#283044",
        "on-surface": "#131b2e",
        "on-secondary-container": "#54647a",
        "error": "#ba1a1a",
        text: {
          primary: '#111827',
          secondary: '#6B7280',
          muted: '#9CA3AF',
        },
        status: {
          success: '#22C55E',
          warning: '#F59E0B',
          danger: '#EF4444',
          info: '#3B82F6',
        }
      },
      spacing: {
        "3xl": "64px",
        "lg": "24px",
        "md": "16px",
        "margin": "32px",
        "unit": "8px",
        "xs": "4px",
        "2xl": "48px",
        "sm": "8px",
        "xl": "32px",
        "gutter": "24px"
      },
      fontFamily: {
        "body-md": ["Geist", "sans-serif"],
        "body-lg": ["Geist", "sans-serif"],
        "label-md": ["Geist", "sans-serif"],
        "headline-xl": ["Geist", "sans-serif"],
        "body-sm": ["Geist", "sans-serif"],
        "mono-md": ["Geist Mono", "monospace"],
        "headline-md": ["Geist", "sans-serif"],
        "headline-lg": ["Geist", "sans-serif"]
      },
      fontSize: {
        "body-md": ["14px", { "lineHeight": "20px", "fontWeight": "400" }],
        "body-lg": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
        "label-md": ["13px", { "lineHeight": "18px", "letterSpacing": "0.05em", "fontWeight": "600" }],
        "headline-xl": ["36px", { "lineHeight": "44px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "body-sm": ["12px", { "lineHeight": "16px", "fontWeight": "400" }],
        "mono-md": ["13px", { "lineHeight": "20px", "fontWeight": "400" }],
        "headline-md": ["20px", { "lineHeight": "28px", "fontWeight": "600" }],
        "headline-lg": ["28px", { "lineHeight": "36px", "letterSpacing": "-0.01em", "fontWeight": "600" }]
      },
      boxShadow: {
        'soft-sm': '0 1px 2px 0 rgba(0, 0, 0, 0.05)',
        'soft-md': '0 4px 6px -1px rgba(0, 0, 0, 0.05), 0 2px 4px -1px rgba(0, 0, 0, 0.03)',
        'soft-lg': '0 10px 15px -3px rgba(0, 0, 0, 0.04), 0 4px 6px -2px rgba(0, 0, 0, 0.02)',
        'soft-xl': '0 20px 25px -5px rgba(0, 0, 0, 0.05), 0 10px 10px -5px rgba(0, 0, 0, 0.02)',
        'ambient': '0 4px 6px -1px rgba(15, 23, 42, 0.05), 0 2px 4px -2px rgba(15, 23, 42, 0.05)',
      },
      borderRadius: {
        '2xl': '1rem',
        '3xl': '1.5rem',
      }
    },
  },
  plugins: [],
}

