"""
seed_sellers_and_properties.py — Seed 2 Sellers and 20 Rich Properties in MongoDB
"""

import os
import django
from datetime import datetime, timezone
from bson import ObjectId

os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'bricklytics_backend.settings')
django.setup()

from django.contrib.auth.hashers import make_password
from accounts.models.user import User
from seller.models.property import Property, PropertyAmenity, PropertyImage
from seller.services.property_service import PropertyService

def seed():
    print("--- Seeding Sellers ---")

    # Seller 1
    s1_email = "seller1@bricklytics.com"
    User.objects.filter(email=s1_email).delete()
    seller1 = User(
        first_name="Rajesh",
        last_name="Patel",
        email=s1_email,
        phone_number="+91 98250 11223",
        password_hash=make_password("Seller@12345"),
        role="seller",
        is_active=True,
        is_verified=True,
    )
    seller1.save()
    s1_id = str(seller1.id)
    print(f"Created Seller 1: {s1_email} (ID: {s1_id})")

    # Seller 2
    s2_email = "seller2@bricklytics.com"
    User.objects.filter(email=s2_email).delete()
    seller2 = User(
        first_name="Ananya",
        last_name="Shah",
        email=s2_email,
        phone_number="+91 98980 44556",
        password_hash=make_password("Seller@12345"),
        role="seller",
        is_active=True,
        is_verified=True,
    )
    seller2.save()
    s2_id = str(seller2.id)
    print(f"Created Seller 2: {s2_email} (ID: {s2_id})")

    # Clean existing properties for these sellers if any
    Property.objects(seller_id__in=[s1_id, s2_id]).delete()

    ps = PropertyService()

    # Define Seller 1 Properties (10 Properties)
    s1_props = [
        {
            "title": "3 BHK Sky High Luxury Apartment in South Bopal",
            "description": "Exquisite 3 BHK apartment featuring panoramic city views, Italian marble flooring, designer modular kitchen, and double-height sunlit balcony.",
            "property_type": "apartment",
            "listing_type": "sell",
            "sale_type": "new",
            "possession_status": "Ready to Move",
            "reconstruction_needed": "",
            "price": 8500000.0,
            "rate_per_sqft": 4594.0,
            "bhk": 3,
            "bedrooms": 3,
            "bathrooms": 3,
            "balconies": 2,
            "area_sqft": 1850.0,
            "built_up_area": 1650.0,
            "super_built_up_area": 1850.0,
            "floor_number": 8,
            "total_floors": 14,
            "property_age": 1,
            "facing": "East",
            "furnishing": "Furnished",
            "parking": "Covered",
            "address": "Skyline Heights, Opposite Applewoods, South Bopal",
            "locality": "South Bopal",
            "city": "Ahmedabad",
            "state": "Gujarat",
            "pincode": "380058",
            "latitude": 23.0185,
            "longitude": 72.4642,
            "maintenance_charges": 2500.0,
            "booking_amount": 500000.0,
            "builder_name": "Skyline Developers",
            "project_name": "Skyline Heights Phase 2",
            "rera_number": "PR/GJ/AHMEDABAD/SANAND/RAA08912/2021",
            "amenities": [
                {"name": "Swimming Pool", "category": "Luxury"},
                {"name": "Fully Equipped Gym", "category": "Fitness"},
                {"name": "EV Charging Station", "category": "Eco"},
                {"name": "Landscaped Garden", "category": "Outdoors"},
                {"name": "24/7 Multi-tier Security", "category": "Safety"},
                {"name": "Clubhouse & Cafe", "category": "Social"},
            ],
            "images_data": [
                {"url": "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?q=80&w=1200", "caption": "Tower Exterior Facade"},
                {"url": "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?q=80&w=1200", "caption": "Spacious Sunlit Living Room"},
                {"url": "https://images.unsplash.com/photo-1556911220-e15b29be8c8f?q=80&w=1200", "caption": "Modern Italian Modular Kitchen"},
                {"url": "https://images.unsplash.com/photo-1616594039964-ae9021a400a0?q=80&w=1200", "caption": "Master Bedroom with Wooden Flooring"},
                {"url": "https://images.unsplash.com/photo-1584622650111-993a426fbf0a?q=80&w=1200", "caption": "En-suite Master Bathroom"},
                {"url": "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?q=80&w=1200", "caption": "Double Height Private Balcony Deck"}
            ]
        },
        {
            "title": "4 BHK Premier Independent Villa in Science City",
            "description": "Architect-designed 4 BHK luxury villa with private plunge pool, private manicured garden, home automation systems, and imported fixture finishings.",
            "property_type": "villa",
            "listing_type": "sell",
            "sale_type": "resale",
            "possession_status": "Ready to Move",
            "reconstruction_needed": "Newly Renovated",
            "price": 24000000.0,
            "rate_per_sqft": 7500.0,
            "bhk": 4,
            "bedrooms": 4,
            "bathrooms": 5,
            "balconies": 3,
            "area_sqft": 3200.0,
            "built_up_area": 3000.0,
            "super_built_up_area": 3200.0,
            "floor_number": 1,
            "total_floors": 2,
            "property_age": 3,
            "facing": "North-East",
            "furnishing": "Semi-Furnished",
            "parking": "Covered",
            "address": "Plot 42, Green Avenue, Near Science City Circle",
            "locality": "Science City",
            "city": "Ahmedabad",
            "state": "Gujarat",
            "pincode": "380060",
            "latitude": 23.0784,
            "longitude": 72.5076,
            "maintenance_charges": 4000.0,
            "booking_amount": 1000000.0,
            "builder_name": "Royal Villa Infra",
            "project_name": "Green Avenue Enclave",
            "amenities": [
                {"name": "Private Plunge Pool", "category": "Luxury"},
                {"name": "Private Garden Lawn", "category": "Outdoors"},
                {"name": "Solar Power Roof", "category": "Eco"},
                {"name": "Home Automation", "category": "Smart"},
                {"name": "Servant Quarters", "category": "Convenience"},
            ],
            "images_data": [
                {"url": "https://images.unsplash.com/photo-1613977257363-707ba9348227?q=80&w=1200", "caption": "Villa Front Elevation & Pool Deck"},
                {"url": "https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?q=80&w=1200", "caption": "Double-Height Grand Living Hall"},
                {"url": "https://images.unsplash.com/photo-1507089947368-19c1da9775ae?q=80&w=1200", "caption": "Open Concept Gourmet Kitchen"},
                {"url": "https://images.unsplash.com/photo-1595526114035-0d45ed16cfbf?q=80&w=1200", "caption": "Master Suite with Garden View"},
                {"url": "https://images.unsplash.com/photo-1552321554-5fefe8c9ef14?q=80&w=1200", "caption": "Designer Bathroom with Jacuzzi Bath"},
                {"url": "https://images.unsplash.com/photo-1533105079780-92b9be482077?q=80&w=1200", "caption": "Private Rooftop Terrace Lounge"}
            ]
        },
        {
            "title": "2 BHK Smart Compact Apartment in Bodakdev",
            "description": "Smartly designed 2 BHK apartment in prime Bodakdev locality. Features optimal space utilization, Vastu compliant layout, and proximity to major IT hubs.",
            "property_type": "apartment",
            "listing_type": "sell",
            "sale_type": "new",
            "possession_status": "Under Construction",
            "reconstruction_needed": "",
            "price": 5800000.0,
            "rate_per_sqft": 4640.0,
            "bhk": 2,
            "bedrooms": 2,
            "bathrooms": 2,
            "balconies": 1,
            "area_sqft": 1250.0,
            "built_up_area": 1100.0,
            "super_built_up_area": 1250.0,
            "floor_number": 4,
            "total_floors": 12,
            "property_age": 0,
            "facing": "East",
            "furnishing": "Semi-Furnished",
            "parking": "Covered",
            "address": "Heights Tower, Judges Bungalow Road, Bodakdev",
            "locality": "Bodakdev",
            "city": "Ahmedabad",
            "state": "Gujarat",
            "pincode": "380054",
            "latitude": 23.0373,
            "longitude": 72.5126,
            "maintenance_charges": 1800.0,
            "booking_amount": 300000.0,
            "builder_name": "Aangan Group",
            "project_name": "Aangan Bodakdev",
            "rera_number": "PR/GJ/AHMEDABAD/BODAKDEV/RAA05411/2023",
            "amenities": [
                {"name": "Clubhouse", "category": "Social"},
                {"name": "Children Play Area", "category": "Family"},
                {"name": "24/7 Security CCTV", "category": "Safety"},
                {"name": "High Speed Elevators", "category": "Convenience"},
            ],
            "images_data": [
                {"url": "https://images.unsplash.com/photo-1567496898669-ee935f5f647a?q=80&w=1200", "caption": "Residential Building View"},
                {"url": "https://images.unsplash.com/photo-1586023492125-27b2c045efd7?q=80&w=1200", "caption": "Warm Cozy Living Room Interior"},
                {"url": "https://images.unsplash.com/photo-1556909212-d5b604d0c90d?q=80&w=1200", "caption": "Parallel Modular Kitchen"},
                {"url": "https://images.unsplash.com/photo-1598928506311-c55ded91a20c?q=80&w=1200", "caption": "Peaceful Master Bedroom"},
                {"url": "https://images.unsplash.com/photo-1620626011761-996317b8d101?q=80&w=1200", "caption": "Clean Modern Bathroom"}
            ]
        },
        {
            "title": "5 BHK Grand Luxury Sky Penthouse on Sindhu Bhavan Road",
            "description": "Ultra-exclusive 5 BHK duplex penthouse overlooking Sindhu Bhavan Road. Includes private infinity glass pool, 3 dedicated car parking slots, and double height sky deck.",
            "property_type": "apartment",
            "listing_type": "sell",
            "sale_type": "resale",
            "possession_status": "Ready to Move",
            "reconstruction_needed": "Fully Reconstructed",
            "price": 48000000.0,
            "rate_per_sqft": 10666.0,
            "bhk": 5,
            "bedrooms": 5,
            "bathrooms": 6,
            "balconies": 4,
            "area_sqft": 4500.0,
            "built_up_area": 4200.0,
            "super_built_up_area": 4500.0,
            "floor_number": 22,
            "total_floors": 22,
            "property_age": 2,
            "facing": "North",
            "furnishing": "Furnished",
            "parking": "Covered",
            "address": "The Pinnacle Penthouse, Sindhu Bhavan Road",
            "locality": "Sindhu Bhavan Road",
            "city": "Ahmedabad",
            "state": "Gujarat",
            "pincode": "380059",
            "latitude": 23.0458,
            "longitude": 72.5034,
            "maintenance_charges": 8000.0,
            "booking_amount": 2500000.0,
            "builder_name": "Pinnacle Realty",
            "project_name": "The Pinnacle SBR",
            "amenities": [
                {"name": "Private Sky Infinity Pool", "category": "Luxury"},
                {"name": "Sky Lounge & Bar Deck", "category": "Social"},
                {"name": "Private High-Speed Elevator", "category": "Luxury"},
                {"name": "3 Dedicated Basement Parking Slots", "category": "Convenience"},
                {"name": "Concierge & Valet Service", "category": "Service"},
            ],
            "images_data": [
                {"url": "https://images.unsplash.com/photo-1512915922686-57c11dde9b6b?q=80&w=1200", "caption": "Sky Penthouse Exterior View"},
                {"url": "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?q=80&w=1200", "caption": "Double-Height Grand Salon Living Area"},
                {"url": "https://images.unsplash.com/photo-1600565193348-f74bd3c7ccdf?q=80&w=1200", "caption": "Italian Designer Marble Island Kitchen"},
                {"url": "https://images.unsplash.com/photo-1600585154526-990dced4db0d?q=80&w=1200", "caption": "Presidential Master Suite with Walk-in Closet"},
                {"url": "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?q=80&w=1200", "caption": "Spa Bathroom with Free-Standing Bathtub"},
                {"url": "https://images.unsplash.com/photo-1507652313519-d4e9174996dd?q=80&w=1200", "caption": "Private Rooftop Deck & Pool Overlooking City"}
            ]
        },
        {
            "title": "3 BHK Elegant Family Flat in Satellite",
            "description": "Well-maintained 3 BHK flat situated in heart of Satellite near Shyamal Cross Roads. Close to top schools, healthcare facilities, and shopping markets.",
            "property_type": "flat",
            "listing_type": "sell",
            "sale_type": "resale",
            "possession_status": "Ready to Move",
            "reconstruction_needed": "Minor Renovation",
            "price": 9200000.0,
            "rate_per_sqft": 5750.0,
            "bhk": 3,
            "bedrooms": 3,
            "bathrooms": 3,
            "balconies": 2,
            "area_sqft": 1600.0,
            "built_up_area": 1450.0,
            "super_built_up_area": 1600.0,
            "floor_number": 5,
            "total_floors": 10,
            "property_age": 5,
            "facing": "West",
            "furnishing": "Furnished",
            "parking": "Covered",
            "address": "Shyamal Enclave, Satellite, Ahmedabad",
            "locality": "Satellite",
            "city": "Ahmedabad",
            "state": "Gujarat",
            "pincode": "380015",
            "latitude": 23.0300,
            "longitude": 72.5270,
            "maintenance_charges": 2200.0,
            "booking_amount": 500000.0,
            "builder_name": "Shyamal Developers",
            "project_name": "Shyamal Enclave",
            "amenities": [
                {"name": "24/7 Security", "category": "Safety"},
                {"name": "Full Power Backup", "category": "Utility"},
                {"name": "Children Play Park", "category": "Family"},
                {"name": "Covered Car Parking", "category": "Convenience"},
            ],
            "images_data": [
                {"url": "https://images.unsplash.com/photo-1570129477492-45c003edd2be?q=80&w=1200", "caption": "Apartment Complex Facade"},
                {"url": "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?q=80&w=1200", "caption": "Furnished Living & Dining Area"},
                {"url": "https://images.unsplash.com/photo-1556912172-45b7abe8b7e1?q=80&w=1200", "caption": "Clean Modular Kitchen Space"},
                {"url": "https://images.unsplash.com/photo-1540518614846-7ede433c5163?q=80&w=1200", "caption": "Comfortable Bedroom"},
                {"url": "https://images.unsplash.com/photo-1507089947368-19c1da9775ae?q=80&w=1200", "caption": "Sunny Balcony Corner"}
            ]
        },
        {
            "title": "1 BHK Modern Studio Apartment in CG Road",
            "description": "Stylish, fully furnished 1 BHK studio apartment on CG Road. High rental demand, turnkey investment opportunity ideal for young professionals or corporate leasing.",
            "property_type": "studio",
            "listing_type": "sell",
            "sale_type": "new",
            "possession_status": "Ready to Move",
            "reconstruction_needed": "",
            "price": 3400000.0,
            "rate_per_sqft": 5230.0,
            "bhk": 1,
            "bedrooms": 1,
            "bathrooms": 1,
            "balconies": 1,
            "area_sqft": 650.0,
            "built_up_area": 580.0,
            "super_built_up_area": 650.0,
            "floor_number": 3,
            "total_floors": 8,
            "property_age": 1,
            "facing": "North",
            "furnishing": "Furnished",
            "parking": "Yes",
            "address": "Urban Studio Towers, Off CG Road, Navrangpura",
            "locality": "CG Road",
            "city": "Ahmedabad",
            "state": "Gujarat",
            "pincode": "380009",
            "latitude": 23.0333,
            "longitude": 72.5621,
            "maintenance_charges": 1200.0,
            "booking_amount": 200000.0,
            "builder_name": "Urban Infra",
            "project_name": "Urban Studio Towers",
            "rera_number": "PR/GJ/AHMEDABAD/CGROAD/RAA02144/2022",
            "amenities": [
                {"name": "Co-Working Lounge", "category": "Business"},
                {"name": "High Speed Elevators", "category": "Convenience"},
                {"name": "24/7 Security", "category": "Safety"},
                {"name": "Laundromat Access", "category": "Service"},
            ],
            "images_data": [
                {"url": "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?q=80&w=1200", "caption": "Studio Living & Workspace Layout"},
                {"url": "https://images.unsplash.com/photo-1556911220-e15b29be8c8f?q=80&w=1200", "caption": "Efficiency Kitchenette"},
                {"url": "https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?q=80&w=1200", "caption": "Cozy Sleeping Nook"},
                {"url": "https://images.unsplash.com/photo-1584622650111-993a426fbf0a?q=80&w=1200", "caption": "Compact Modern Bathroom"}
            ]
        },
        {
            "title": "Commercial Office Space on SG Highway",
            "description": "Grade-A corporate office space on SG Highway near ISCON Cross Roads. Bare-shell layout ready for custom office fitouts with glass curtain walling.",
            "property_type": "commercial",
            "listing_type": "sell",
            "sale_type": "new",
            "possession_status": "Under Construction",
            "reconstruction_needed": "",
            "price": 17500000.0,
            "rate_per_sqft": 8333.0,
            "bhk": 1,
            "bedrooms": 0,
            "bathrooms": 2,
            "balconies": 0,
            "area_sqft": 2100.0,
            "built_up_area": 1900.0,
            "super_built_up_area": 2100.0,
            "floor_number": 7,
            "total_floors": 18,
            "property_age": 0,
            "facing": "East",
            "furnishing": "Unfurnished",
            "parking": "Covered",
            "address": "Monolith Business Park, SG Highway",
            "locality": "SG Highway",
            "city": "Ahmedabad",
            "state": "Gujarat",
            "pincode": "380015",
            "latitude": 23.0276,
            "longitude": 72.5070,
            "maintenance_charges": 5000.0,
            "booking_amount": 1000000.0,
            "builder_name": "Monolith Group",
            "project_name": "Monolith Business Park",
            "rera_number": "PR/GJ/AHMEDABAD/SGHIGHWAY/RAA09901/2023",
            "amenities": [
                {"name": "Centralized VRV AC Provision", "category": "Utility"},
                {"name": "100% DG Power Backup", "category": "Utility"},
                {"name": "Grand Reception Lobby", "category": "Business"},
                {"name": "4 High Speed Passenger Elevators", "category": "Convenience"},
                {"name": "3 Level Basement Parking", "category": "Convenience"},
            ],
            "images_data": [
                {"url": "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?q=80&w=1200", "caption": "Commercial Glass Tower Facade"},
                {"url": "https://images.unsplash.com/photo-1497366216548-37526070297c?q=80&w=1200", "caption": "Open Plan Workfloor Concept"},
                {"url": "https://images.unsplash.com/photo-1497215728101-856f4ea42174?q=80&w=1200", "caption": "Executive Cabin & Conference View"},
                {"url": "https://images.unsplash.com/photo-1504384308090-c894fdcc538d?q=80&w=1200", "caption": "Corporate Entrance Lobby"}
            ]
        },
        {
            "title": "4 BHK Heritage Style Bungalow House in Ambli",
            "description": "Sprawling 4 BHK independent bungalow nestled in serene greens of Ambli. Includes central private courtyard, servant quarter, and room for private pool.",
            "property_type": "house",
            "listing_type": "sell",
            "sale_type": "resale",
            "possession_status": "Ready to Move",
            "reconstruction_needed": "Never Renovated",
            "price": 31000000.0,
            "rate_per_sqft": 8157.0,
            "bhk": 4,
            "bedrooms": 4,
            "bathrooms": 4,
            "balconies": 2,
            "area_sqft": 3800.0,
            "built_up_area": 3500.0,
            "super_built_up_area": 3800.0,
            "floor_number": 1,
            "total_floors": 2,
            "property_age": 8,
            "facing": "East",
            "furnishing": "Unfurnished",
            "parking": "Covered",
            "address": "Bungalow No 14, Ambli Bopal Road",
            "locality": "Ambli",
            "city": "Ahmedabad",
            "state": "Gujarat",
            "pincode": "380058",
            "latitude": 23.0335,
            "longitude": 72.4760,
            "maintenance_charges": 3000.0,
            "booking_amount": 1500000.0,
            "builder_name": "Ambli Estates",
            "project_name": "Ambli Greens Enclave",
            "amenities": [
                {"name": "Lush Courtyard Garden", "category": "Outdoors"},
                {"name": "Servant Quarters", "category": "Convenience"},
                {"name": "Covered 2-Car Garage", "category": "Convenience"},
                {"name": "Gated Security Community", "category": "Safety"},
            ],
            "images_data": [
                {"url": "https://images.unsplash.com/photo-1580587771525-78b9dba3b914?q=80&w=1200", "caption": "Bungalow Entrance Elevation"},
                {"url": "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?q=80&w=1200", "caption": "Traditional Living Room Hall"},
                {"url": "https://images.unsplash.com/photo-1556911220-e15b29be8c8f?q=80&w=1200", "caption": "Spacious Kitchen Space"},
                {"url": "https://images.unsplash.com/photo-1616594039964-ae9021a400a0?q=80&w=1200", "caption": "Master Bed Chamber"},
                {"url": "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?q=80&w=1200", "caption": "Internal Courtyard Garden View"}
            ]
        },
        {
            "title": "Prime Residential Plot / Land in Shela",
            "description": "Clear title 2400 sqft residential plot located in prime gated township in Shela. Ready for immediate construction with full infrastructure ready.",
            "property_type": "plot",
            "listing_type": "sell",
            "sale_type": "new",
            "possession_status": "Ready to Move",
            "reconstruction_needed": "",
            "price": 11500000.0,
            "rate_per_sqft": 4791.0,
            "bhk": 1,
            "bedrooms": 0,
            "bathrooms": 0,
            "balconies": 0,
            "area_sqft": 2400.0,
            "built_up_area": 0.0,
            "super_built_up_area": 2400.0,
            "floor_number": 0,
            "total_floors": 0,
            "property_age": 0,
            "facing": "East",
            "furnishing": "Unfurnished",
            "parking": "Open",
            "address": "Plot No 88, Royal Meadows Township, Shela",
            "locality": "Shela",
            "city": "Ahmedabad",
            "state": "Gujarat",
            "pincode": "380058",
            "latitude": 23.0030,
            "longitude": 72.4490,
            "maintenance_charges": 1000.0,
            "booking_amount": 500000.0,
            "builder_name": "Royal Meadows Infra",
            "project_name": "Royal Meadows Shela",
            "rera_number": "PR/GJ/AHMEDABAD/SANAND/RAA01088/2021",
            "amenities": [
                {"name": "Gated Community Entry Arch", "category": "Safety"},
                {"name": "40ft Wide Internal Asphalt Roads", "category": "Infra"},
                {"name": "Underground Electricity & Water", "category": "Infra"},
                {"name": "Township Club Access", "category": "Social"},
            ],
            "images_data": [
                {"url": "https://images.unsplash.com/photo-1500382017468-9049fed747ef?q=80&w=1200", "caption": "Residential Plot Layout View"},
                {"url": "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?q=80&w=1200", "caption": "Surrounding Open Greenery & Township Roads"}
            ]
        },
        {
            "title": "2 BHK Premium City Apartment in Prahlad Nagar",
            "description": "Vastu compliant 2 BHK apartment in prime Prahlad Nagar location near Corporate Road. Excellent cross ventilation and pipeline gas connection.",
            "property_type": "apartment",
            "listing_type": "sell",
            "sale_type": "resale",
            "possession_status": "Ready to Move",
            "reconstruction_needed": "Major Renovation",
            "price": 6800000.0,
            "rate_per_sqft": 5230.0,
            "bhk": 2,
            "bedrooms": 2,
            "bathrooms": 2,
            "balconies": 1,
            "area_sqft": 1300.0,
            "built_up_area": 1180.0,
            "super_built_up_area": 1300.0,
            "floor_number": 6,
            "total_floors": 11,
            "property_age": 6,
            "facing": "North-East",
            "furnishing": "Semi-Furnished",
            "parking": "Covered",
            "address": "Corporate Heights, Near Prahlad Nagar Garden",
            "locality": "Prahlad Nagar",
            "city": "Ahmedabad",
            "state": "Gujarat",
            "pincode": "380015",
            "latitude": 23.0120,
            "longitude": 72.5110,
            "maintenance_charges": 1800.0,
            "booking_amount": 400000.0,
            "builder_name": "Corporate Realty",
            "project_name": "Corporate Heights",
            "amenities": [
                {"name": "Piped Gas Connection", "category": "Utility"},
                {"name": "Covered Basement Parking", "category": "Convenience"},
                {"name": "24/7 Security", "category": "Safety"},
                {"name": "Kids Play Area", "category": "Family"},
            ],
            "images_data": [
                {"url": "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?q=80&w=1200", "caption": "Apartment Building View"},
                {"url": "https://images.unsplash.com/photo-1586023492125-27b2c045efd7?q=80&w=1200", "caption": "Living & Dining Room Interior"},
                {"url": "https://images.unsplash.com/photo-1556911220-e15b29be8c8f?q=80&w=1200", "caption": "Modular Kitchen Setup"},
                {"url": "https://images.unsplash.com/photo-1598928506311-c55ded91a20c?q=80&w=1200", "caption": "Master Bedroom Area"},
                {"url": "https://images.unsplash.com/photo-1620626011761-996317b8d101?q=80&w=1200", "caption": "Clean Bathroom"}
            ]
        }
    ]

    # Define Seller 2 Properties (10 Properties)
    s2_props = [
        {
            "title": "3 BHK Sky Villa Apartment in Thaltej",
            "description": "Ultra modern 3 BHK sky villa in Thaltej with double height balcony, infinity rooftop pool, and 3-side open layout.",
            "property_type": "apartment",
            "listing_type": "sell",
            "sale_type": "new",
            "possession_status": "Under Construction",
            "reconstruction_needed": "",
            "price": 14500000.0,
            "rate_per_sqft": 6904.0,
            "bhk": 3,
            "bedrooms": 3,
            "bathrooms": 3,
            "balconies": 2,
            "area_sqft": 2100.0,
            "built_up_area": 1900.0,
            "super_built_up_area": 2100.0,
            "floor_number": 11,
            "total_floors": 16,
            "property_age": 0,
            "facing": "East",
            "furnishing": "Semi-Furnished",
            "parking": "Covered",
            "address": "Aura Sky Villas, Near Hebatpur Road, Thaltej",
            "locality": "Thaltej",
            "city": "Ahmedabad",
            "state": "Gujarat",
            "pincode": "380059",
            "latitude": 23.0500,
            "longitude": 72.5170,
            "maintenance_charges": 3500.0,
            "booking_amount": 800000.0,
            "builder_name": "Aura Heights",
            "project_name": "Aura Sky Villas",
            "rera_number": "PR/GJ/AHMEDABAD/THALTEJ/RAA04499/2023",
            "amenities": [
                {"name": "Rooftop Infinity Pool", "category": "Luxury"},
                {"name": "Sky Deck Lounge", "category": "Social"},
                {"name": "EV Charging Station", "category": "Eco"},
                {"name": "Squash Court & Gym", "category": "Sports"},
            ],
            "images_data": [
                {"url": "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?q=80&w=1200", "caption": "Tower Architectural Elevation"},
                {"url": "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?q=80&w=1200", "caption": "Luxurious Sunlit Living Room"},
                {"url": "https://images.unsplash.com/photo-1556911220-e15b29be8c8f?q=80&w=1200", "caption": "Island Modular Kitchen"},
                {"url": "https://images.unsplash.com/photo-1616594039964-ae9021a400a0?q=80&w=1200", "caption": "Master Suite Bedroom"},
                {"url": "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?q=80&w=1200", "caption": "High Floor Sunset Balcony"}
            ]
        },
        {
            "title": "2 BHK Smart Compact Flat in Gota",
            "description": "Well connected 2 BHK flat near SG Highway in Gota. Affordable family home with low maintenance and ready amenities.",
            "property_type": "flat",
            "listing_type": "sell",
            "sale_type": "resale",
            "possession_status": "Ready to Move",
            "reconstruction_needed": "Minor Renovation",
            "price": 4800000.0,
            "rate_per_sqft": 4173.0,
            "bhk": 2,
            "bedrooms": 2,
            "bathrooms": 2,
            "balconies": 1,
            "area_sqft": 1150.0,
            "built_up_area": 1020.0,
            "super_built_up_area": 1150.0,
            "floor_number": 3,
            "total_floors": 9,
            "property_age": 4,
            "facing": "North",
            "furnishing": "Semi-Furnished",
            "parking": "Covered",
            "address": "Vande Mataram Icon, Gota, Ahmedabad",
            "locality": "Gota",
            "city": "Ahmedabad",
            "state": "Gujarat",
            "pincode": "382481",
            "latitude": 23.1020,
            "longitude": 72.5350,
            "maintenance_charges": 1500.0,
            "booking_amount": 300000.0,
            "builder_name": "Vande Mataram Group",
            "project_name": "Vande Mataram Icon",
            "amenities": [
                {"name": "Community Hall", "category": "Social"},
                {"name": "Jogging Track", "category": "Fitness"},
                {"name": "24/7 Security", "category": "Safety"},
            ],
            "images_data": [
                {"url": "https://images.unsplash.com/photo-1567496898669-ee935f5f647a?q=80&w=1200", "caption": "Gota Apartment Elevation"},
                {"url": "https://images.unsplash.com/photo-1586023492125-27b2c045efd7?q=80&w=1200", "caption": "Living Hall Area"},
                {"url": "https://images.unsplash.com/photo-1556909212-d5b604d0c90d?q=80&w=1200", "caption": "Kitchen Workspace"},
                {"url": "https://images.unsplash.com/photo-1598928506311-c55ded91a20c?q=80&w=1200", "caption": "Bedroom View"}
            ]
        },
        {
            "title": "4 BHK Designer Duplex Villa in Chandkheda",
            "description": "Luxurious 4 BHK duplex villa near SP Ring Road, Chandkheda. Features private terrace garden, Italian sanitaryware, and wooden paneling.",
            "property_type": "villa",
            "listing_type": "sell",
            "sale_type": "resale",
            "possession_status": "Ready to Move",
            "reconstruction_needed": "Newly Renovated",
            "price": 21000000.0,
            "rate_per_sqft": 7241.0,
            "bhk": 4,
            "bedrooms": 4,
            "bathrooms": 4,
            "balconies": 2,
            "area_sqft": 2900.0,
            "built_up_area": 2700.0,
            "super_built_up_area": 2900.0,
            "floor_number": 1,
            "total_floors": 2,
            "property_age": 2,
            "facing": "East",
            "furnishing": "Furnished",
            "parking": "Covered",
            "address": "Villa 18, Royal Palms, Chandkheda",
            "locality": "Chandkheda",
            "city": "Ahmedabad",
            "state": "Gujarat",
            "pincode": "382424",
            "latitude": 23.1150,
            "longitude": 72.5850,
            "maintenance_charges": 3200.0,
            "booking_amount": 1000000.0,
            "builder_name": "Royal Infra",
            "project_name": "Royal Palms Villas",
            "amenities": [
                {"name": "Private Terrace Garden", "category": "Outdoors"},
                {"name": "Landscaped Courtyard", "category": "Outdoors"},
                {"name": "Home Theatre Lounge", "category": "Entertainment"},
                {"name": "24/7 Gated Security", "category": "Safety"},
            ],
            "images_data": [
                {"url": "https://images.unsplash.com/photo-1613977257363-707ba9348227?q=80&w=1200", "caption": "Duplex Villa Front View"},
                {"url": "https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?q=80&w=1200", "caption": "High Ceiling Living Room"},
                {"url": "https://images.unsplash.com/photo-1507089947368-19c1da9775ae?q=80&w=1200", "caption": "Modern Open Kitchen & Island"},
                {"url": "https://images.unsplash.com/photo-1595526114035-0d45ed16cfbf?q=80&w=1200", "caption": "Master Suite Bedroom"},
                {"url": "https://images.unsplash.com/photo-1552321554-5fefe8c9ef14?q=80&w=1200", "caption": "Spa Bathroom"}
            ]
        },
        {
            "title": "3 BHK Spacious Garden Flat in Naranpura",
            "description": "3 BHK spacious flat in peaceful Naranpura residential sector. Cross-ventilated layout with large balconies and modular fittings.",
            "property_type": "apartment",
            "listing_type": "sell",
            "sale_type": "resale",
            "possession_status": "Ready to Move",
            "reconstruction_needed": "Never Renovated",
            "price": 9800000.0,
            "rate_per_sqft": 5600.0,
            "bhk": 3,
            "bedrooms": 3,
            "bathrooms": 3,
            "balconies": 2,
            "area_sqft": 1750.0,
            "built_up_area": 1600.0,
            "super_built_up_area": 1750.0,
            "floor_number": 4,
            "total_floors": 7,
            "property_age": 7,
            "facing": "North-East",
            "furnishing": "Unfurnished",
            "parking": "Covered",
            "address": "Kavita Society, Naranpura, Ahmedabad",
            "locality": "Naranpura",
            "city": "Ahmedabad",
            "state": "Gujarat",
            "pincode": "380013",
            "latitude": 23.0560,
            "longitude": 72.5530,
            "maintenance_charges": 2000.0,
            "booking_amount": 500000.0,
            "builder_name": "Kavita Developers",
            "project_name": "Kavita Society",
            "amenities": [
                {"name": "Clubhouse & Gym", "category": "Social"},
                {"name": "Badminton Court", "category": "Sports"},
                {"name": "Covered Car Parking", "category": "Convenience"},
            ],
            "images_data": [
                {"url": "https://images.unsplash.com/photo-1570129477492-45c003edd2be?q=80&w=1200", "caption": "Apartment Building View"},
                {"url": "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?q=80&w=1200", "caption": "Spacious Living Room Hall"},
                {"url": "https://images.unsplash.com/photo-1556912172-45b7abe8b7e1?q=80&w=1200", "caption": "Kitchen Setup"},
                {"url": "https://images.unsplash.com/photo-1540518614846-7ede433c5163?q=80&w=1200", "caption": "Master Bedroom Area"}
            ]
        },
        {
            "title": "4 BHK Luxury Apartment in Navrangpura",
            "description": "High-end 4 BHK residence in heart of Navrangpura near Commerce Six Roads. Equipped with smart digital locks and premium wooden flooring.",
            "property_type": "apartment",
            "listing_type": "sell",
            "sale_type": "new",
            "possession_status": "Ready to Move",
            "reconstruction_needed": "",
            "price": 18500000.0,
            "rate_per_sqft": 7708.0,
            "bhk": 4,
            "bedrooms": 4,
            "bathrooms": 4,
            "balconies": 3,
            "area_sqft": 2400.0,
            "built_up_area": 2200.0,
            "super_built_up_area": 2400.0,
            "floor_number": 9,
            "total_floors": 12,
            "property_age": 1,
            "facing": "East",
            "furnishing": "Furnished",
            "parking": "Covered",
            "address": "Navrang One, Commerce Six Roads, Navrangpura",
            "locality": "Navrangpura",
            "city": "Ahmedabad",
            "state": "Gujarat",
            "pincode": "380009",
            "latitude": 23.0380,
            "longitude": 72.5560,
            "maintenance_charges": 4000.0,
            "booking_amount": 1000000.0,
            "builder_name": "Navrang Infra",
            "project_name": "Navrang One Towers",
            "rera_number": "PR/GJ/AHMEDABAD/NAVRANGPURA/RAA03112/2022",
            "amenities": [
                {"name": "Concierge Desk", "category": "Service"},
                {"name": "Digital Smart Door Locks", "category": "Smart"},
                {"name": "Fitness Gym & Sauna", "category": "Fitness"},
                {"name": "2 Covered Parking Slots", "category": "Convenience"},
            ],
            "images_data": [
                {"url": "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?q=80&w=1200", "caption": "Luxury Tower Architecture"},
                {"url": "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?q=80&w=1200", "caption": "Designer Living Room with Chandelier"},
                {"url": "https://images.unsplash.com/photo-1556911220-e15b29be8c8f?q=80&w=1200", "caption": "Premium Island Kitchen"},
                {"url": "https://images.unsplash.com/photo-1616594039964-ae9021a400a0?q=80&w=1200", "caption": "Master Bedroom Suite"},
                {"url": "https://images.unsplash.com/photo-1584622650111-993a426fbf0a?q=80&w=1200", "caption": "Modern En-Suite Bath"}
            ]
        },
        {
            "title": "2 BHK City View Apartment in Paldi",
            "description": "Completely renovated 2 BHK apartment in prime Paldi near NID. Offers stunning Sabarmati riverfront views and modern interiors.",
            "property_type": "flat",
            "listing_type": "sell",
            "sale_type": "resale",
            "possession_status": "Ready to Move",
            "reconstruction_needed": "Fully Reconstructed",
            "price": 7200000.0,
            "rate_per_sqft": 5333.0,
            "bhk": 2,
            "bedrooms": 2,
            "bathrooms": 2,
            "balconies": 1,
            "area_sqft": 1350.0,
            "built_up_area": 1200.0,
            "super_built_up_area": 1350.0,
            "floor_number": 6,
            "total_floors": 8,
            "property_age": 5,
            "facing": "West",
            "furnishing": "Furnished",
            "parking": "Covered",
            "address": "Riverview Heights, Near NID, Paldi",
            "locality": "Paldi",
            "city": "Ahmedabad",
            "state": "Gujarat",
            "pincode": "380007",
            "latitude": 23.0130,
            "longitude": 72.5650,
            "maintenance_charges": 1900.0,
            "booking_amount": 400000.0,
            "builder_name": "Riverview Realty",
            "project_name": "Riverview Heights",
            "amenities": [
                {"name": "Solar Common Lighting", "category": "Eco"},
                {"name": "Children Play Zone", "category": "Family"},
                {"name": "24/7 Security", "category": "Safety"},
            ],
            "images_data": [
                {"url": "https://images.unsplash.com/photo-1567496898669-ee935f5f647a?q=80&w=1200", "caption": "Riverfront Tower Facade"},
                {"url": "https://images.unsplash.com/photo-1586023492125-27b2c045efd7?q=80&w=1200", "caption": "Cozy Living Room Hall"},
                {"url": "https://images.unsplash.com/photo-1556909212-d5b604d0c90d?q=80&w=1200", "caption": "Sleek Modular Kitchen"},
                {"url": "https://images.unsplash.com/photo-1598928506311-c55ded91a20c?q=80&w=1200", "caption": "Bedroom Area"},
                {"url": "https://images.unsplash.com/photo-1507089947368-19c1da9775ae?q=80&w=1200", "caption": "Balcony with City Views"}
            ]
        },
        {
            "title": "Commercial Retail Store on Sindhu Bhavan Road",
            "description": "High visibility ground floor retail store on Sindhu Bhavan Road boulevard. Huge glass frontage, high footfall, ideal for luxury boutique or cafe.",
            "property_type": "commercial",
            "listing_type": "sell",
            "sale_type": "new",
            "possession_status": "Ready to Move",
            "reconstruction_needed": "",
            "price": 12500000.0,
            "rate_per_sqft": 13157.0,
            "bhk": 1,
            "bedrooms": 0,
            "bathrooms": 1,
            "balconies": 0,
            "area_sqft": 950.0,
            "built_up_area": 900.0,
            "super_built_up_area": 950.0,
            "floor_number": 0,
            "total_floors": 4,
            "property_age": 1,
            "facing": "North",
            "furnishing": "Unfurnished",
            "parking": "Open",
            "address": "Ground Floor, SBR Retail Plaza, Sindhu Bhavan Road",
            "locality": "Sindhu Bhavan Road",
            "city": "Ahmedabad",
            "state": "Gujarat",
            "pincode": "380059",
            "latitude": 23.0465,
            "longitude": 72.5020,
            "maintenance_charges": 3000.0,
            "booking_amount": 800000.0,
            "builder_name": "SBR Developers",
            "project_name": "SBR Retail Plaza",
            "rera_number": "PR/GJ/AHMEDABAD/SBR/RAA09120/2022",
            "amenities": [
                {"name": "High Glass Frontage", "category": "Business"},
                {"name": "Promenade Parking Plaza", "category": "Convenience"},
                {"name": "24/7 Security & CCTV", "category": "Safety"},
            ],
            "images_data": [
                {"url": "https://images.unsplash.com/photo-1441986300917-64674bd600d8?q=80&w=1200", "caption": "Retail Store Frontage Exterior"},
                {"url": "https://images.unsplash.com/photo-1497366216548-37526070297c?q=80&w=1200", "caption": "Store Interior Workfloor Space"},
                {"url": "https://images.unsplash.com/photo-1504384308090-c894fdcc538d?q=80&w=1200", "caption": "Boulevard Plaza View"}
            ]
        },
        {
            "title": "5 BHK Ultra Luxury Independent House in Bodakdev",
            "description": "Palatial 5 BHK independent residence in Bodakdev with private elevator, heated swimming pool, 4-car garage, and private manicured lawn.",
            "property_type": "house",
            "listing_type": "sell",
            "sale_type": "resale",
            "possession_status": "Ready to Move",
            "reconstruction_needed": "Minor Renovation",
            "price": 42000000.0,
            "rate_per_sqft": 10000.0,
            "bhk": 5,
            "bedrooms": 5,
            "bathrooms": 6,
            "balconies": 3,
            "area_sqft": 4200.0,
            "built_up_area": 4000.0,
            "super_built_up_area": 4200.0,
            "floor_number": 1,
            "total_floors": 3,
            "property_age": 4,
            "facing": "East",
            "furnishing": "Semi-Furnished",
            "parking": "Covered",
            "address": "Bungalow No 7, Bodakdev Enclave",
            "locality": "Bodakdev",
            "city": "Ahmedabad",
            "state": "Gujarat",
            "pincode": "380054",
            "latitude": 23.0390,
            "longitude": 72.5100,
            "maintenance_charges": 5000.0,
            "booking_amount": 2000000.0,
            "builder_name": "Bodakdev Infra",
            "project_name": "Bodakdev Enclave",
            "amenities": [
                {"name": "Private Elevator", "category": "Luxury"},
                {"name": "Heated Outdoor Pool", "category": "Luxury"},
                {"name": "4-Car Covered Garage", "category": "Convenience"},
                {"name": "Manicured Lawn & Gazebo", "category": "Outdoors"},
            ],
            "images_data": [
                {"url": "https://images.unsplash.com/photo-1613977257363-707ba9348227?q=80&w=1200", "caption": "Grand Mansion Facade & Driveway"},
                {"url": "https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?q=80&w=1200", "caption": "Royal Living Hall with Marble Flooring"},
                {"url": "https://images.unsplash.com/photo-1507089947368-19c1da9775ae?q=80&w=1200", "caption": "Chef's Kitchen with Pantry"},
                {"url": "https://images.unsplash.com/photo-1595526114035-0d45ed16cfbf?q=80&w=1200", "caption": "Master Suite Bed Chamber"},
                {"url": "https://images.unsplash.com/photo-1552321554-5fefe8c9ef14?q=80&w=1200", "caption": "Luxury Spa Bathroom"}
            ]
        },
        {
            "title": "3 BHK High Floor Flat in Science City",
            "description": "Panoramic 3 BHK high-floor residence in Science City. Features unobstructed green views, EV charging bay, and smart security systems.",
            "property_type": "apartment",
            "listing_type": "sell",
            "sale_type": "new",
            "possession_status": "Under Construction",
            "reconstruction_needed": "",
            "price": 11000000.0,
            "rate_per_sqft": 5789.0,
            "bhk": 3,
            "bedrooms": 3,
            "bathrooms": 3,
            "balconies": 2,
            "area_sqft": 1900.0,
            "built_up_area": 1720.0,
            "super_built_up_area": 1900.0,
            "floor_number": 12,
            "total_floors": 18,
            "property_age": 0,
            "facing": "North",
            "furnishing": "Semi-Furnished",
            "parking": "Covered",
            "address": "Science Park Towers, Science City Road",
            "locality": "Science City",
            "city": "Ahmedabad",
            "state": "Gujarat",
            "pincode": "380060",
            "latitude": 23.0800,
            "longitude": 72.5050,
            "maintenance_charges": 2800.0,
            "booking_amount": 600000.0,
            "builder_name": "Science Park Infra",
            "project_name": "Science Park Towers",
            "rera_number": "PR/GJ/AHMEDABAD/SCIENCECITY/RAA07890/2023",
            "amenities": [
                {"name": "EV Charging Station", "category": "Eco"},
                {"name": "Multi-Sports Court", "category": "Sports"},
                {"name": "Sky Deck Balcony", "category": "Social"},
            ],
            "images_data": [
                {"url": "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?q=80&w=1200", "caption": "Modern High-Rise Tower Architecture"},
                {"url": "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?q=80&w=1200", "caption": "Sunlit Living Room View"},
                {"url": "https://images.unsplash.com/photo-1556911220-e15b29be8c8f?q=80&w=1200", "caption": "Modular Kitchen Area"},
                {"url": "https://images.unsplash.com/photo-1616594039964-ae9021a400a0?q=80&w=1200", "caption": "Master Bedroom Area"}
            ]
        },
        {
            "title": "1 BHK Executive Studio Apartment in Memnagar",
            "description": "Compact 1 BHK executive apartment in Memnagar near Subhash Bridge. Ideal for bachelor executives or students, turnkey ready.",
            "property_type": "studio",
            "listing_type": "sell",
            "sale_type": "resale",
            "possession_status": "Ready to Move",
            "reconstruction_needed": "Newly Renovated",
            "price": 3900000.0,
            "rate_per_sqft": 5200.0,
            "bhk": 1,
            "bedrooms": 1,
            "bathrooms": 1,
            "balconies": 1,
            "area_sqft": 750.0,
            "built_up_area": 680.0,
            "super_built_up_area": 750.0,
            "floor_number": 2,
            "total_floors": 6,
            "property_age": 3,
            "facing": "East",
            "furnishing": "Furnished",
            "parking": "Yes",
            "address": "Memnagar Executive Hub, Memnagar",
            "locality": "Memnagar",
            "city": "Ahmedabad",
            "state": "Gujarat",
            "pincode": "380052",
            "latitude": 23.0500,
            "longitude": 72.5400,
            "maintenance_charges": 1400.0,
            "booking_amount": 250000.0,
            "builder_name": "Memnagar Infra",
            "project_name": "Executive Hub",
            "amenities": [
                {"name": "Fitness Center Gym", "category": "Fitness"},
                {"name": "24/7 Security", "category": "Safety"},
            ],
            "images_data": [
                {"url": "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?q=80&w=1200", "caption": "Compact Executive Living Room"},
                {"url": "https://images.unsplash.com/photo-1556911220-e15b29be8c8f?q=80&w=1200", "caption": "Efficiency Kitchen"},
                {"url": "https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?q=80&w=1200", "caption": "Bed Room Nook"},
                {"url": "https://images.unsplash.com/photo-1584622650111-993a426fbf0a?q=80&w=1200", "caption": "Modern Bathroom"}
            ]
        }
    ]

    print("\n--- Inserting Seller 1 Properties ---")
    for idx, raw in enumerate(s1_props, 1):
        imgs_meta = raw.pop('images_data', [])
        images_list = []
        for i_idx, img_item in enumerate(imgs_meta):
            images_list.append(PropertyImage(
                id=str(ObjectId()),
                url=img_item['url'],
                file_path=img_item['url'],
                is_cover=(i_idx == 0),
                caption=img_item['caption'],
                created_at=datetime.now(timezone.utc)
            ))
        
        prop_payload = {
            **raw,
            'seller_id': s1_id,
            'seller_name': seller1.full_name,
            'phone_number': seller1.phone_number,
            'email': seller1.email,
            'status': 'active',
            'images': images_list,
        }
        created = ps.create_property(prop_payload)
        print(f"[{idx}/10] Created Seller 1 Prop: {created['title']} (ID: {created['id']})")

    print("\n--- Inserting Seller 2 Properties ---")
    for idx, raw in enumerate(s2_props, 1):
        imgs_meta = raw.pop('images_data', [])
        images_list = []
        for i_idx, img_item in enumerate(imgs_meta):
            images_list.append(PropertyImage(
                id=str(ObjectId()),
                url=img_item['url'],
                file_path=img_item['url'],
                is_cover=(i_idx == 0),
                caption=img_item['caption'],
                created_at=datetime.now(timezone.utc)
            ))
        
        prop_payload = {
            **raw,
            'seller_id': s2_id,
            'seller_name': seller2.full_name,
            'phone_number': seller2.phone_number,
            'email': seller2.email,
            'status': 'active',
            'images': images_list,
        }
        created = ps.create_property(prop_payload)
        print(f"[{idx}/10] Created Seller 2 Prop: {created['title']} (ID: {created['id']})")

    print("\n=== Seeding Finished Successfully ===")

if __name__ == '__main__':
    seed()
