# Generated by Django 6.0.6 on 2026-07-06 12:54

import django.contrib.gis.db.models.fields
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailVerificationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('code', models.CharField(max_length=6)),
                ('purpose', models.CharField(choices=[('register', 'Register Verification'), ('reset', 'Password Reset')], max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(default='overpass', help_text='overpass | google_places', max_length=32)),
                ('source_id', models.CharField(db_index=True, help_text="Provider's own ID, for dedupe.", max_length=128)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('subtype', models.CharField(choices=[('school', 'School'), ('college', 'College'), ('daycare', 'Daycare'), ('fire_station', 'Fire Station'), ('police_station', 'Police Station'), ('hospital', 'Hospital'), ('pharmacy', 'Pharmacy'), ('urgent_care', 'Urgent Care Clinic'), ('subway', 'Subway Station'), ('bus_stop', 'Bus Stop'), ('train', 'Train Hub')], max_length=32)),
                ('category', models.CharField(choices=[('education', 'Education'), ('safety', 'Emergency & Safety'), ('healthcare', 'Healthcare'), ('mobility', 'Mobility / Transit'), ('traffic', 'Traffic & Congestion')], max_length=32)),
                ('location', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
                ('raw_tags', models.JSONField(blank=True, default=dict)),
                ('fetched_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['category', 'subtype'], name='core_amenit_categor_35a4e5_idx')],
                'constraints': [models.UniqueConstraint(fields=('source', 'source_id'), name='unique_amenity_source')],
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(blank=True, db_index=True, help_text='ID from the source listing feed, if any.', max_length=128)),
                ('title', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=500)),
                ('location', django.contrib.gis.db.models.fields.PointField(geography=True, help_text='WGS84 lon/lat of the property.', srid=4326)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('bedrooms', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('bathrooms', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('listing_type', models.CharField(choices=[('sale', 'For Sale'), ('rent', 'For Rent')], default='sale', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['is_active', 'listing_type'], name='core_proper_is_acti_54b0d9_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserPreferenceProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Default', max_length=100)),
                ('weight_education', models.PositiveSmallIntegerField(default=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('weight_safety', models.PositiveSmallIntegerField(default=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('weight_healthcare', models.PositiveSmallIntegerField(default=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('weight_mobility', models.PositiveSmallIntegerField(default=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('weight_traffic', models.PositiveSmallIntegerField(default=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('search_radius_meters', models.PositiveIntegerField(default=2000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preference_profiles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MatchScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_score', models.FloatField(help_text='0-100 final weighted match score.')),
                ('category_breakdown', models.JSONField(default=dict, help_text="{'education': {'raw_score': .., 'weight': .., 'contribution': ..}, ...}")),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_scores', to='core.property')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_scores', to='core.userpreferenceprofile')),
            ],
            options={
                'ordering': ['-total_score'],
            },
        ),
        migrations.CreateModel(
            name='PropertyAmenityLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance_meters', models.FloatField()),
                ('estimated_travel_seconds', models.PositiveIntegerField(blank=True, help_text='Driving ETA if a routing lookup was done; else null (straight-line only).', null=True)),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('amenity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_links', to='core.amenity')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amenity_links', to='core.property')),
            ],
            options={
                'indexes': [models.Index(fields=['property', 'amenity'], name='core_proper_propert_77e2ac_idx')],
                'constraints': [models.UniqueConstraint(fields=('property', 'amenity'), name='unique_property_amenity')],
            },
        ),
        migrations.CreateModel(
            name='TrafficSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(default='tomtom', max_length=16)),
                ('congestion_index', models.FloatField(help_text='0.0 (free-flow) to 1.0 (gridlock), provider-normalized.')),
                ('avg_commute_seconds_peak', models.PositiveIntegerField(blank=True, help_text='Avg commute time during peak hours, if available.', null=True)),
                ('current_speed_kph', models.FloatField(blank=True, null=True)),
                ('free_flow_speed_kph', models.FloatField(blank=True, null=True)),
                ('captured_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traffic_snapshots', to='core.property')),
            ],
            options={
                'get_latest_by': 'captured_at',
                'indexes': [models.Index(fields=['property', 'captured_at'], name='core_traffi_propert_1797b6_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='userpreferenceprofile',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='unique_profile_name_per_user'),
        ),
        migrations.AddConstraint(
            model_name='matchscore',
            constraint=models.UniqueConstraint(fields=('property', 'profile'), name='unique_score_per_profile'),
        ),
    ]
